# Generated by Django 3.0.5 on 2020-05-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
