# Generated by Django 3.0.5 on 2020-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
